# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfeed', '0006_auto_20180308_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
