# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 13:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfeed', '0007_auto_20180309_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
