# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfeed', '0008_auto_20180309_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
