# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfeed', '0009_auto_20180309_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.TextField(),
        ),
    ]
