# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfeed', '0010_auto_20180309_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='{ media/user_pictures }'),
        ),
    ]
