# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodfeed', '0013_auto_20180309_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 13, 56, 25, 815109, tzinfo=utc)),
        ),
    ]
