# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 14:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfeed', '0014_auto_20180309_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 9, 14, 7, 13, 124905)),
        ),
    ]
