# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 11:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfeed', '0015_auto_20180309_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 10, 11, 30, 14, 458619)),
        ),
    ]
