# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 12:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfeed', '0017_auto_20180310_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 10, 12, 56, 9, 86553)),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_pictures'),
        ),
    ]
