# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 13:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfeed', '0020_auto_20180312_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 12, 13, 46, 40, 492825)),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_pictures'),
        ),
    ]
