# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 17:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfeed', '0024_auto_20180312_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 12, 17, 49, 8, 583249)),
        ),
    ]
