# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfeed', '0027_auto_20180312_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 13, 10, 36, 0, 93000)),
        ),
    ]
