# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfeed', '0030_auto_20180313_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='cooking_rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='health_rating',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='rating',
            name='style_rating',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='picture',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 15, 17, 18, 47, 921931)),
        ),
    ]
