# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 19:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodfeed', '0031_auto_20180315_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 15, 19, 20, 5, 974245)),
        ),
    ]
